import { HStack } from "@chakra-ui/react";
import Image from "next/image";

export function DevImg({
  imgWidth,
  imgHeight,
}: {
  imgWidth: number;
  imgHeight: number;
}) {
  return (
    <HStack width={"full"} wrap={"wrap"}>
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="TypeScript"
        src="https://img.shields.io/badge/TypeScript-007ACC?style=for-the-badge&logo=typescript&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="React"
        src="https://img.shields.io/badge/React-20232A?style=for-the-badge&logo=react&logoColor=61DAFB"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="React_Native"
        src="https://img.shields.io/badge/React_Native-20232A?style=for-the-badge&logo=react&logoColor=61DAFB"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Chakra"
        src="https://img.shields.io/badge/Chakra--UI-319795?style=for-the-badge&logo=chakra-ui&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Vercel"
        src="https://img.shields.io/badge/Vercel-000000?style=for-the-badge&logo=vercel&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Netlify"
        src="https://img.shields.io/badge/Netlify-00C7B7?style=for-the-badge&logo=netlify&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="firebase"
        src="https://img.shields.io/badge/firebase-ffca28?style=for-the-badge&logo=firebase&logoColor=black"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="GitHub"
        src="https://img.shields.io/badge/GitHub%20Pages-222222?style=for-the-badge&logo=GitHub%20Pages&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Jest"
        src="https://img.shields.io/badge/Jest-C21325?style=for-the-badge&logo=jest&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="next"
        src="https://img.shields.io/badge/next.js-000000?style=for-the-badge&logo=nextdotjs&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Sass"
        src="https://img.shields.io/badge/Sass-CC6699?style=for-the-badge&logo=sass&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="mac"
        src="https://img.shields.io/badge/mac%20os-000000?style=for-the-badge&logo=apple&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Vite"
        src="https://img.shields.io/badge/Vite-B73BFE?style=for-the-badge&logo=vite&logoColor=FFD62E"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Yarn"
        src="https://img.shields.io/badge/Yarn-2C8EBB?style=for-the-badge&logo=yarn&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="VSCode"
        src="https://img.shields.io/badge/VSCode-0078D4?style=for-the-badge&logo=visual%20studio%20code&logoColor=white"
      />

      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Adobe"
        src="https://img.shields.io/badge/Adobe%20Creative%20Cloud-DA1F26?style=for-the-badge&logo=Adobe%20Creative%20ClogoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Amazon_AWS"
        src="https://img.shields.io/badge/Amazon_AWS-FF9900?style=for-the-badge&logo=amazonaws&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Ant"
        src="https://img.shields.io/badge/Ant%20Design-1890FF?style=for-the-badge&logo=antdesign&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Apollo"
        src="https://img.shields.io/badge/Apollo%20GraphQL-311C87?&style=for-the-badge&logo=Apollo%20GraphQL&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Azure_Functions"
        src="https://img.shields.io/badge/Azure_Functions-0062AD?style=for-the-badge&logo=azure-functions&logoColor=wh"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Babel"
        src="https://img.shields.io/badge/Babel-F9DC3E?style=for-the-badge&logo=babel&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Canva"
        src="https://img.shields.io/badge/Canva-%2300C4CC.svg?&style=for-the-badge&logo=Canva&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="cocoapods"
        src="https://img.shields.io/badge/cocoapods-FA2A02?style=for-the-badge&logo=cocoapods&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="CSS3"
        src="https://img.shields.io/badge/CSS3-1572B6?style=for-the-badge&logo=css3&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Cypress"
        src="https://img.shields.io/badge/Cypress-17202C?style=for-the-badge&logo=cypress&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="D3"
        src="https://img.shields.io/badge/d3.js-F9A03C?style=for-the-badge&logo=d3.js&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="dev"
        src="https://img.shields.io/badge/dev.to-0A0A0A?style=for-the-badge&logo=devdotto&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Django"
        src="https://img.shields.io/badge/Django-092E20?style=for-the-badge&logo=django&logoColor=green"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Docker"
        src="https://img.shields.io/badge/Docker-2CA5E0?style=for-the-badge&logo=docker&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="eslint"
        src="https://img.shields.io/badge/eslint-3A33D1?style=for-the-badge&logo=eslint&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Express"
        src="https://img.shields.io/badge/Express.js-000000?style=for-the-badge&logo=express&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Figma"
        src="https://img.shields.io/badge/Figma-F24E1E?style=for-the-badge&logo=figma&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Gatsby"
        src="https://img.shields.io/badge/Gatsby-663399?style=for-the-badge&logo=gatsby&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="GIT"
        src="https://img.shields.io/badge/GIT-E44C30?style=for-the-badge&logo=git&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Github"
        src="https://img.shields.io/badge/Github%20Actions-282a2e?style=for-the-badge&logo=githubactions&logoColor=367cfe"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Go"
        src="https://img.shields.io/badge/Go-00ADD8?style=for-the-badge&logo=go&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Google"
        src="https://img.shields.io/badge/Google%20Analytics-E37400?style=for-the-badge&logo=google%20analytics&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="GraphQl"
        src="https://img.shields.io/badge/GraphQl-E10098?style=for-the-badge&logo=graphql&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Gulp"
        src="https://img.shields.io/badge/Gulp-CF4647?style=for-the-badge&logo=gulp&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Handlebars"
        src="https://img.shields.io/badge/Handlebars.js-f0772b?style=for-the-badge&logo=handlebarsdotjs&logoColor=black"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Handlebars"
        src="https://img.shields.io/badge/Hugo-FF4088?style=for-the-badge&logo=hugo&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Heroku"
        src="https://img.shields.io/badge/Heroku-430098?style=for-the-badge&logo=heroku&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="JavaScript"
        src="https://img.shields.io/badge/JavaScript-323330?style=for-the-badge&logo=javascript&logoColor=F7DF1E"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Jira"
        src="https://img.shields.io/badge/Jira-0052CC?style=for-the-badge&logo=Jira&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="json"
        src="https://img.shields.io/badge/json-5E5C5C?style=for-the-badge&logo=json&logoColor=whitehttps://img.shields.io/bHTML5-E34F26?style=for-the-badge&logo=html5&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="JSS"
        src="https://img.shields.io/badge/JSS-F7DF1E?style=for-the-badge&logo=JSS&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="JWT"
        src="https://img.shields.io/badge/JWT-000000?style=for-the-badge&logo=JSON%20web%20tokens&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Kibana"
        src="https://img.shields.io/badge/Kibana-005571?style=for-the-badge&logo=Kibana&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Lerna"
        src="https://img.shields.io/badge/Lerna-3E3E3E?style=for-the-badge&logo=lerna&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Linux"
        src="https://img.shields.io/badge/Linux-FCC624?style=for-the-badge&logo=linux&logoColor=black"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Markdown"
        src="https://img.shields.io/badge/Markdown-000000?style=for-the-badge&logo=markdown&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Material"
        src="https://img.shields.io/badge/Material%20UI-007FFF?style=for-the-badge&logo=mui&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Microsoft"
        src="https://img.shields.io/badge/Microsoft-666666?style=for-the-badge&logo=microsoft&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Mocha"
        src="https://img.shields.io/badge/Mocha-8D6748?style=for-the-badge&logo=Mocha&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="MongoDB"
        src="https://img.shields.io/badge/MongoDB-4EA94B?style=for-the-badge&logo=mongodb&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="MySQL"
        src="https://img.shields.io/badge/MySQL-005C84?style=for-the-badge&logo=mysql&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Nginx"
        src="https://img.shields.io/badge/Nginx-009639?style=for-the-badge&logo=nginx&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Node"
        src="https://img.shields.io/badge/Node.js-339933?style=for-the-badge&logo=nodedotjs&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="npm"
        src="https://img.shields.io/badge/npm-CB3837?style=for-the-badge&logo=npm&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="PHP"
        src="https://img.shields.io/badge/PHP-777BB4?style=for-the-badge&logo=php&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="PostgreSQL"
        src="https://img.shields.io/badge/PostgreSQL-316192?style=for-the-badge&logo=postgresql&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Postman"
        src="https://img.shields.io/badge/Postman-FF6C37?style=for-the-badge&logo=Postman&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="PowerBI"
        src="https://img.shields.io/badge/PowerBI-F2C811?style=for-the-badge&logo=Power%20BI&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="powershell"
        src="https://img.shields.io/badge/powershell-5391FE?style=for-the-badge&logo=powershell&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="prettier"
        src="https://img.shields.io/badge/prettier-1A2C34?style=for-the-badge&logo=prettier&logoColor=F7BA3E"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Raspberry"
        src="https://img.shields.io/badge/Raspberry%20Pi-A22846?style=for-the-badge&logo=Raspberry%20Pi&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="redis"
        src="https://img.shields.io/badge/redis-%23DD0031.svg?&style=for-the-badge&logo=redis&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Redux"
        src="https://img.shields.io/badge/Redux-593D88?style=for-the-badge&logo=redux&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="shopify"
        src="https://img.shields.io/badge/shopify-8DB543?style=for-the-badge&logo=Shopify&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="storybook"
        src="https://img.shields.io/badge/storybook-FF4785?style=for-the-badge&logo=storybook&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Stripe"
        src="https://img.shields.io/badge/Stripe-626CD9?style=for-the-badge&logo=Stripe&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="styled"
        src="https://img.shields.io/badge/styled--components-DB7093?style=for-the-badge&logo=styled-components&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="sublime_text"
        src="https://img.shields.io/badge/sublime_text-%23575757.svg?&style=for-the-badge&logo=sublime-logoColor=important"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="ts-node"
        src="https://img.shields.io/badge/ts--node-3178C6?style=for-the-badge&logo=ts-node&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="VirtualBox"
        src="https://img.shields.io/badge/VirtualBox-21416b?style=for-the-badge&logo=VirtualBox&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="VMware"
        src="https://img.shields.io/badge/VMware-231f20?style=for-the-badge&logo=VMware&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Vue"
        src="https://img.shields.io/badge/Vue.js-35495E?style=for-the-badge&logo=vuedotjs&logoColor=4FC08D"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Webpack"
        src="https://img.shields.io/badge/Webpack-8DD6F9?style=for-the-badge&logo=Webpack&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Windows"
        src="https://img.shields.io/badge/Windows-0078D6?style=for-the-badge&logo=windows&logoColor=white"
      />
      <Image
        width={imgWidth}
        height={imgHeight}
        alt="Wordpress"
        src="https://img.shields.io/badge/Wordpress-21759B?style=for-the-badge&logo=wordpress&logoColor=white"
      />
    </HStack>
  );
}
